### ISSUE TITLE
BUG - Sidebar open button – only reacting when clicking directly on the Icon.

### ISSUE THREAD

**Issue by KarloDerEchte** [Karlo-Hosting/Docs#2]
The "Click"-Cursor shows when hovering over the green shown box/div. But doesn't open the Sidebar, it opens it when you're directly clicking on the Icon itself, which can be confusing.

![image](https://github.com/Karlo-Hosting/Docs/assets/41088744/e842dcee-bea4-49f2-963d-5dffd2047f7b)

**Comment by phil-flip** [comment]
Should get fixed with the new CSS.

**Comment by phil-flip** [comment]
@KarloDerEchte Please verify, if this issue is still present.

**Comment by KarloDerEchte** [comment]
Jo passt erstmal
